### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by vltansky** [vltansky/next-swiper-website#2]
- [x] Github stats
- [x] Prism svelte
- [x] Homepage changelog
- [x] Header package version
- [x] Homepage Gallery Slider
- [x] Homepage slider perfomance
- [x] Demos
- [x] Api page
- [x] SEO
- [ ] Speed optimizations (homepage logos, etc.)
- [x] Design issues
